language: node_js
install:
  - npm install
script:
  - npm install codecov -g
  - npm run nyc
  - npm run codecov
  - codecov -f test/report/*.json

after_success:
  - codecov
node_js:
  - 12
  - 14
services: mongodb
